# Generated by Django 4.2 on 2024-07-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='people',
            field=models.IntegerField(),
        ),
    ]
