# Generated by Django 4.2 on 2024-07-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantly', '0003_contect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contect',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contect',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contect',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contect',
            old_name='Subject',
            new_name='subject',
        ),
    ]
